dwca-avro:
  inputPath: /data/dwca-export/{datasetId}/{datasetId}.zip
  #inputPath: /data/dwca-export/{datasetId}/tmp
  tempLocation: /data/dwca-export/{datasetId}/tmp/
uuid:
  numberOfBackupsToKeep: 5
alaNameMatch:
  wsUrl: https://namematching.biodiversitydata.se/
sds:
  wsUrl: https://sensitive.biodiversitydata.se/
collectory:
  wsUrl: https://collections.biodiversitydata.se/ws/
  #wsUrl: http://localhost:8080/ws/
  httpHeaders:
    Authorization:
imageService:
  #wsUrl: https://images.biodiversitydata.se/ws/
  wsUrl: http://localhost:8082/
  httpHeaders:
    apiKey:
speciesListService:
  wsUrl: https://lists.biodiversitydata.se
samplingService:
  wsUrl: https://spatial.biodiversitydata.se/ws/
  batchStatusSleepTime: 10000
index:
  includeImages: false
jackKnife:
  layers: el10014,el10016
solr:
  #zkHost: localhost:2181,localhost:2182,localhost:2183
  zkHost: localhost:9983
  includeSampling: true
  includeClustering: true
  includeJackKnife: false
  numOfPartitions: 2
geocodeConfig:
  stateProvince:
    path: /data/pipelines-shp/lan
    field: LnNamn
images:
  # pipe separated list (note: YAML list not coming through correctly)
  recognisedPaths: "https://images.biodiversitydata.se|http://localhost:8082"
  sleepTimeInMillis: 10000
export:
  imageServicePath: "https://images.biodiversitydata.se/image/proxyImageThumbnailLarge?imageId={0}"
locationInfoConfig:
#    countryNamesFile : /data/pipelines-data/resources/countries.txt
#    countryCentrePointsFile : /data/pipelines-data/resources/countryCentrePoints.txt
#    stateProvinceCentrePointsFile : /data/pipelines-data/resources/stateProvinceCentrePoints.txt
    stateProvinceNamesFile : /data/pipelines-data/resources/stateProvinces.tsv
recordedByConfig:
  cacheSizeMb: 1000000
#sampling:
#  keepLatLngExports: true
