# which filesystem to use: local or hdfs

general:
  attempt: 1
  hdfsSiteConfig: /Users/mar759/dev/hadoop/etc/hadoop/hdfs-site.xml
  coreSiteConfig: /Users/mar759/dev/hadoop/etc/hadoop/core-site.xml

annotation:
  inputPath: hdfs://localhost:9000/pipelines-annotations
  targetPath: hdfs://localhost:9000/pipelines-annotations

collectory:
  wsUrl: http://dev.ala.org.au:8082/ws/

elastic:
  esSchemaPath: /Users/mar759/dev/pipelines/livingatlas/pipelines/src/test/resources/complete-event-pipeline/es-event-core-schema.json