log4j.rootLogger=WARN, consoleAppender

log4j.appender.consoleAppender=org.apache.log4j.ConsoleAppender
log4j.appender.consoleAppender.layout=org.apache.log4j.PatternLayout
log4j.appender.consoleAppender.layout.ConversionPattern=%-5p [%d{yyyy-MM-dd HH:mm:ss,SSSZ}] [%t] %c: %m%n

log4j.logger.au.org.ala=INFO, consoleAppender
log4j.additivity.au.org.ala=false

log4j.logger.au.org.ala.pipelines.vocabulary.StateProvinceParser=ERROR, consoleAppender
log4j.additivity.au.org.ala.pipelines.vocabulary.StateProvinceParser=false

log4j.logger.org.gbif=INFO, consoleAppender
log4j.additivity.org.gbif=false

log4j.logger.org.gbif.common.parsers=ERROR, consoleAppender
log4j.additivity.org.gbif.common.parsers=false

log4j.logger.org.gbif.dwc.terms.TermFactory=ERROR, consoleAppender
log4j.additivity.org.gbif.dwc.terms.TermFactory=false

log4j.logger.org.apache.avro.Schema=ERROR, consoleAppender
log4j.additivity.org.apache.avro.Schema=false

log4j.logger.org.apache.beam.runners.spark.translation=ERROR, consoleAppender
log4j.additivity.org.apache.beam.runners.spark.translation=false

log4j.logger.org.apache.beam.sdk.io.FileBasedSink=ERROR, consoleAppender
log4j.additivity.org.apache.beam.sdk.io.FileBasedSink=false

log4j.logger.org.apache.beam.sdk.Pipeline=ERROR, consoleAppender
log4j.additivity.org.apache.beam.sdk.Pipeline=false
