#!/bin/bash

# Exit on errors
set -e

SECONDS=0
dr=$1
image_flag=$2
dr_data=/data/pipelines-data/$dr/1
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

$scriptpath/la-pipelines copy $dr
$scriptpath/la-pipelines dwca-avro $dr
$scriptpath/la-pipelines interpret $dr --embedded
$scriptpath/la-pipelines uuid $dr --embedded
$scriptpath/la-pipelines sds $dr --embedded
#if grep -q multimediaRecordsCountAttempted "$dr_data/interpretation-metrics.yml"; then
if [ "$image_flag" = "--load-images" ]; then
  $scriptpath/la-pipelines image-load $dr --embedded
  $scriptpath/la-pipelines image-sync $dr --embedded
  extra_args_index="--extra-args=includeImages=true"
fi
$scriptpath/la-pipelines index $dr --embedded $extra_args_index
$scriptpath/la-pipelines sample $dr --embedded
if [ ! -d "$dr_data/sampling" ]; then
  extra_args_solr="--extra-args=includeSampling=false"
fi
$scriptpath/la-pipelines solr $dr --embedded $extra_args_solr

duration=$SECONDS
echo "=== load-dr of $dr took $(($duration / 60)) minutes and $(($duration % 60)) seconds"
